<a href="https://colab.research.google.com/github/JuniorTorresMTJ/-Exercises-_of_Python/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Conhecendo numpy e suas funções

In [1]:
import pandas as pd
import numpy as np

Criando um Array 

In [2]:
a = np.array([1,2,3])

Somando 1,5 em todos os elementos do Array

In [15]:
b =a + 1.5
b

array([2.5, 3.5, 4.5])

Arredondando todos os elementos

In [16]:
c = np.around(b)

In [17]:
c

array([2., 4., 4.])

Copiar o Array com a função Flatten (Array C é igual ao Array D)

In [18]:
d = c.flatten()

In [19]:
d

array([2., 4., 4.])

Repetindo cada elemento do Array

In [20]:
r= np.repeat(a,3)

In [21]:
r

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

Repetindo todos os elementos do  Array

In [23]:
t =  np.tile(a,3)
t

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

FIM
