<a href="https://colab.research.google.com/github/JuniorTorresMTJ/-Exercises-_of_Python/blob/master/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Criação e Manipulação de Series



In [3]:
import pandas as pd
from pandas import Series

Verificando a Versão do Pandas

In [4]:
pd.__version__

'1.0.5'

Criando uma Series com Index automatico



In [5]:
obj = pd.Series([67,78,-56, 13])

In [6]:
obj

0    67
1    78
2   -56
3    13
dtype: int64

Verificando o tipo da Serie

In [7]:
type(obj)

pandas.core.series.Series

Verificando os Valores da Serie

In [8]:
obj.values

array([ 67,  78, -56,  13])

Imprimindo os Index 

In [9]:
obj.index

RangeIndex(start=0, stop=4, step=1)

Especificando os valores e os Index


In [10]:
obj2= Series([67,78,-56,13], index = ['a','b','c','d'])

In [11]:
obj2

a    67
b    78
c   -56
d    13
dtype: int64

Mostrando os Valores


In [12]:
obj.values

array([ 67,  78, -56,  13])

Fazendo um Filtro e mostrando todos os valores maiores que 3

In [13]:
obj2[obj2>3]

a    67
b    78
d    13
dtype: int64

Mostrar o Valor no indice B

In [14]:
obj2['b']

78

outra forma de fazer uma consulta


In [15]:
'd' in obj2

True

Criando um Dicionário


In [16]:
dict = {'Futebol':5200, 'Tenis': 120, 'Natação': 698, 'Voleibol': 1550}

In [17]:
obj3 = Series(dict)

In [18]:
obj3

Futebol     5200
Tenis        120
Natação      698
Voleibol    1550
dtype: int64

Verificando o tipo


In [19]:
type(obj3)

pandas.core.series.Series

In [20]:
esportes = ['Futebol','Tenis','Natação','Handbol']

Criando uma série com o indice "esportes"

In [21]:
obj4 = Series(dict, index = esportes)

In [22]:
obj4

Futebol    5200.0
Tenis       120.0
Natação     698.0
Handbol       NaN
dtype: float64

Verificados os valores Null

In [23]:
pd.isnull(obj4)

Futebol    False
Tenis      False
Natação    False
Handbol     True
dtype: bool

Verificando os não nulos

In [24]:
pd.notnull(obj4)

Futebol     True
Tenis       True
Natação     True
Handbol    False
dtype: bool

Outra maneira de verificar

In [25]:
obj4.isnull()

Futebol    False
Tenis      False
Natação    False
Handbol     True
dtype: bool

Concatenando Series

In [26]:
obj3 + obj4

Futebol     10400.0
Handbol         NaN
Natação      1396.0
Tenis         240.0
Voleibol        NaN
dtype: float64

Mudando o título

In [27]:
obj4.name = 'população'

mudando o título do indice

In [28]:
obj4.index.name = 'esporte'

In [29]:
obj4

esporte
Futebol    5200.0
Tenis       120.0
Natação     698.0
Handbol       NaN
Name: população, dtype: float64

# Criando e Manipulando um DataFrame

In [30]:
from pandas import DataFrame

Criando um DataFrame

In [31]:
data = {'Estado': ['Santa Catarina', 'Paraná', 'Goiás', 'Bahia', 'Minas Gerais'], 
        'Ano': [2002, 2003, 2004, 2005, 2006], 
        'População': [1.5, 1.7, 3.6, 2.4, 2.9]}

In [32]:
frame = DataFrame(data)

Mudando os títulos das Colunas

In [33]:
DataFrame(data, columns=['Ano', 'Estado','População'])

Ano          Estado  População
0  2002  Santa Catarina        1.5
1  2003          Paraná        1.7
2  2004           Goiás        3.6
3  2005           Bahia        2.4
4  2006    Minas Gerais        2.9

Criando outro DataFrame


In [34]:
frame2 = DataFrame(data, columns = ['Ano', 'Estado', 'População', 'Débito'], 
                   index = ['um', 'dois', 'três', 'quatro', 'cinco'])

Imprimindo o DataFrame

In [35]:
frame2

Ano          Estado  População Débito
um      2002  Santa Catarina        1.5    NaN
dois    2003          Paraná        1.7    NaN
três    2004           Goiás        3.6    NaN
quatro  2005           Bahia        2.4    NaN
cinco   2006    Minas Gerais        2.9    NaN

Pegando os dados da coluna Estado

In [36]:
frame2['Estado']

um        Santa Catarina
dois              Paraná
três               Goiás
quatro             Bahia
cinco       Minas Gerais
Name: Estado, dtype: object

Verificando o tipo do DataFrame

In [37]:
type(frame2)

pandas.core.frame.DataFrame

Verificando o Index

In [38]:
frame2.index

Index(['um', 'dois', 'três', 'quatro', 'cinco'], dtype='object')

Verificando as Colunas

In [39]:
frame2.columns

Index(['Ano', 'Estado', 'População', 'Débito'], dtype='object')

Verificando os Valores

In [40]:
frame2.values

array([[2002, 'Santa Catarina', 1.5, nan],
       [2003, 'Paraná', 1.7, nan],
       [2004, 'Goiás', 3.6, nan],
       [2005, 'Bahia', 2.4, nan],
       [2006, 'Minas Gerais', 2.9, nan]], dtype=object)

Vendo os Tipos de dados de cada coluna

In [41]:
frame.dtypes

Estado        object
Ano            int64
População    float64
dtype: object

Vendo apenas os dados da coluna Ano

In [42]:
frame2['Ano']

um        2002
dois      2003
três      2004
quatro    2005
cinco     2006
Name: Ano, dtype: int64

Vendo de outra forma

In [43]:
frame2.Ano

um        2002
dois      2003
três      2004
quatro    2005
cinco     2006
Name: Ano, dtype: int64

Fazendo Slicing 

In [44]:
frame2[:2]

Ano          Estado  População Débito
um    2002  Santa Catarina        1.5    NaN
dois  2003          Paraná        1.7    NaN

In [48]:
import numpy as np


frame2['Débito']= np.arange(5.)

In [51]:
frame2

Ano          Estado  População  Débito
um      2002  Santa Catarina        1.5     0.0
dois    2003          Paraná        1.7     1.0
três    2004           Goiás        3.6     2.0
quatro  2005           Bahia        2.4     3.0
cinco   2006    Minas Gerais        2.9     4.0

In [52]:
frame2.values

array([[2002, 'Santa Catarina', 1.5, 0.0],
       [2003, 'Paraná', 1.7, 1.0],
       [2004, 'Goiás', 3.6, 2.0],
       [2005, 'Bahia', 2.4, 3.0],
       [2006, 'Minas Gerais', 2.9, 4.0]], dtype=object)

In [58]:
frame2.describe()

#STD é o desvio Padrão

Ano  População    Débito
count     5.000000   5.000000  5.000000
mean   2004.000000   2.420000  2.000000
std       1.581139   0.864292  1.581139
min    2002.000000   1.500000  0.000000
25%    2003.000000   1.700000  1.000000
50%    2004.000000   2.400000  2.000000
75%    2005.000000   2.900000  3.000000
max    2006.000000   3.600000  4.000000

Fazendo um Slicing

In [55]:
frame2['dois':'quatro']

Ano  Estado  População  Débito
dois    2003  Paraná        1.7     1.0
três    2004   Goiás        3.6     2.0
quatro  2005   Bahia        2.4     3.0

Localizando Registros dentro do Dataframe


In [60]:
frame2.loc['quatro']

Ano           2005
Estado       Bahia
População      2.4
Débito           3
Name: quatro, dtype: object

Localização pelo índice


In [61]:
frame2.iloc[2]

Ano           2004
Estado       Goiás
População      3.6
Débito           2
Name: três, dtype: object

In [62]:
#criando um dicionário
web_stats = {'Dias':[1, 2, 3 , 4, 5, 6, 7],
             'Visitantes':[45,23,67,78,23,12,14],
             'Taxas':[11,22,23,44,55,66,77]}

In [63]:
df= pd.DataFrame(web_stats)

In [64]:
print(df)

   Dias  Visitantes  Taxas
0     1          45     11
1     2          23     22
2     3          67     23
3     4          78     44
4     5          23     55
5     6          12     66
6     7          14     77


Como a dias é uma sequência de números, vou deixa-lá como meu index. Para isso precisa usar a função set_index

In [66]:
print(df.set_index('Dias'))

      Visitantes  Taxas
Dias                   
1             45     11
2             23     22
3             67     23
4             78     44
5             23     55
6             12     66
7             14     77


Para visualizar apenas as primeiras linhas, utiliza-se a função head(), por default, a função head são 5 primeiras linhas, mas se você colocar um número poderá ser mais que 5

In [67]:
df.head()

Dias  Visitantes  Taxas
0     1          45     11
1     2          23     22
2     3          67     23
3     4          78     44
4     5          23     55

In [69]:
df.head(7)

Dias  Visitantes  Taxas
0     1          45     11
1     2          23     22
2     3          67     23
3     4          78     44
4     5          23     55
5     6          12     66
6     7          14     77

In [72]:
print(df['Visitantes'])

0    45
1    23
2    67
3    78
4    23
5    12
6    14
Name: Visitantes, dtype: int64


Visualizando apenas uma coluna


In [73]:
df['Visitantes']

0    45
1    23
2    67
3    78
4    23
5    12
6    14
Name: Visitantes, dtype: int64

Visualizando mais de uma coluna


In [77]:
df[['Visitantes', 'Taxas']]

Visitantes  Taxas
0          45     11
1          23     22
2          67     23
3          78     44
4          23     55
5          12     66
6          14     77

Mudando a ordem de visualização

In [78]:
df[['Taxas','Visitantes']]

Taxas  Visitantes
0     11          45
1     22          23
2     23          67
3     44          78
4     55          23
5     66          12
6     77          14

# Manipulando Arquivos


Usuando função read_csv


In [80]:
df= pd.read_csv('https://raw.githubusercontent.com/dsacademybr/PythonFundamentos/master/Cap08/Notebooks/salarios.csv')

In [81]:
df

Name  ... Employee Annual Salary
0          AARON,  ELVIA J  ...              $88965.00
1        AARON,  JEFFERY M  ...              $80778.00
2           AARON,  KARINA  ...              $80778.00
3      AARON,  KIMBERLEI R  ...              $84780.00
4      ABAD JR,  VICENTE M  ...             $104736.00
...                    ...  ...                    ...
32177   ZYGOWICZ,  PETER J  ...              $86520.00
32178    ZYMANTAS,  MARK E  ...              $83616.00
32179  ZYRKOWSKI,  CARLO E  ...              $86520.00
32180  ZYSKOWSKI,  DARIUSZ  ...             $110352.00
32181                  NaN  ...                    NaN

[32182 rows x 4 columns]

Usando read_table

In [82]:
df = pd.read_table('https://raw.githubusercontent.com/dsacademybr/PythonFundamentos/master/Cap08/Notebooks/salarios.csv', sep = ',')

In [83]:
df

Name  ... Employee Annual Salary
0          AARON,  ELVIA J  ...              $88965.00
1        AARON,  JEFFERY M  ...              $80778.00
2           AARON,  KARINA  ...              $80778.00
3      AARON,  KIMBERLEI R  ...              $84780.00
4      ABAD JR,  VICENTE M  ...             $104736.00
...                    ...  ...                    ...
32177   ZYGOWICZ,  PETER J  ...              $86520.00
32178    ZYMANTAS,  MARK E  ...              $83616.00
32179  ZYRKOWSKI,  CARLO E  ...              $86520.00
32180  ZYSKOWSKI,  DARIUSZ  ...             $110352.00
32181                  NaN  ...                    NaN

[32182 rows x 4 columns]

Para usar no Windons use !type e no Mac ou Linux use !head

In [84]:
!head salarios.csv

head: cannot open 'salarios.csv' for reading: No such file or directory


Mudando os títulos das colunas


In [85]:
df= pd.read_csv('https://raw.githubusercontent.com/dsacademybr/PythonFundamentos/master/Cap08/Notebooks/salarios.csv', names = ['a', 'b', 'c', 'd'])

In [87]:
df.head()

a  ...                       d
0                 Name  ...  Employee Annual Salary
1      AARON,  ELVIA J  ...               $88965.00
2    AARON,  JEFFERY M  ...               $80778.00
3       AARON,  KARINA  ...               $80778.00
4  AARON,  KIMBERLEI R  ...               $84780.00

[5 rows x 4 columns]

In [88]:
import sys

Comando para salvar toda a manipulação em um arquivo CSV separados por pipeline

In [ ]:
data.to_csv(sys.stdout, sep ='|')

Criando um DataFrame com o index são as datas e com dados randomicos. 

In [90]:
#Criando um DataFrame

dates = pd.date_range('20200101', periods=10)
#range de 10 datas iniciando com 20200101
df = pd.DataFrame(np.random.randn(10,4), index = dates, columns=list('ABCD'))
#gerando dados randomicos para popular a tabela, com indice sendo as datas e as colunas com títulos A,B,C,D
df

A         B         C         D
2020-01-01 -1.199450  0.546110  0.565547  1.650190
2020-01-02  0.860479 -0.760395  0.371678 -0.167800
2020-01-03 -0.538002 -1.030120 -2.993862  1.230291
2020-01-04  0.345409  0.060058 -0.423333  0.765457
2020-01-05  0.645649 -2.008271  0.321339  0.025149
2020-01-06 -0.472700 -0.340600  0.274690 -0.255787
2020-01-07 -0.900482 -1.031559  0.936371  0.487478
2020-01-08 -0.265991  0.142812  0.134106 -0.953731
2020-01-09  1.307839 -0.564258  1.072039 -0.660030
2020-01-10 -1.445053 -0.070487  1.065641  0.317379